spring.application.name=conquier
spring.liquibase.enabled=false  
server.port=8081


#db
spring.datasource.url=jdbc:mysql://localhost:3306/conquiere
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=MYSQL

#H2
spring.h2.console.enabled=false

#Swagger
springdoc.swagger-ui.path=/swagger-ui-custom.html


# Configuration des endpoints Actuator
 #metrics,loggers,env,mappings
management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.server.port=8082



#jwt
jwt.secret=jxyg3lJ789Kmn4opqrs6tuvwxyza0b1c2d3e4f5g6h7i8j9klmnopqrstuvwxyzABCDEFGHIJKLMN
jwt.prefix=TBASS
jwt.header=Authorization
jwt.access.token.expiration=600000
jwt.refresh.token.expiration=3600000

#url frontend 

conquiere.url.angular=http://localhost:4200


